spring:
  jackson:
    default-property-inclusion: non-absent
    serialization:
      write-dates-as-timestamps: false
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/application
    username: application
    password: application
    tomcat:
      default-auto-commit: true
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-idle: 50
      time-between-eviction-runs-millis: 5000
      test-while-idle: true
      validation-query: SELECT 1
      jmx-enabled: true

logging:
  file: biotope-tools.log
  path: logs
  pattern:
    console: '[%-5p] %d | %c{1}:%L | %m%n'
    file: '[%-5p] %d | %c{1}:%L | %m%n'
  level:
    liquibase: INFO
    org.springframework: ERROR
    org.springframework.boot: ERROR
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web: ERROR
    org.springframework.web.servlet.DispatcherServlet: ERROR
    org.springframework.security: ERROR
    org.springframework.security.web.FilterChainProxy: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    brussels.bric: DEBUG